### ISSUE TITLE
[Feature Suggestion] Dwitter Embed

### ISSUE THREAD

**Issue by xen-the** [lionleaf/dwitter#220]
Could use Dwitter.net/e/#### for embed on external sites just like youtube embed.
Once requested it fetch's the dweets code and responds with standalone player...

`<canvas id="c"width="1920"height="1080"style="width:100%"><script>c=document.body.childNodes[0];with(Math)S=sin,C=cos,T=tan;function R(r,g,b,a){a=a===undefined?1:a;return "rgba("+(r|0)+","+(g|0)+","+(b|0)+","+a+")"};x=c.getContext("2d");frame=0;function u(){t=++frame/60;
//dweet below
for(i=c.width|=0;i--;x.fillRect(960+S(p=1.047*i+S(t/5)*3e3/i*S(t))*(d=i*i/1e3)-i*C(t),540+C(p)*d-i*S(t),s,s))x.fillStyle=R(i*t%99,i/t,s=i/5)
//
requestAnimationFrame(u)}u()</script>`

**Comment by sigvef** [comment]
All dweets already are embeds on dwitter.net, actually! Just put https://dweet.dwitter.net/id/3218?autoplay=1 in an iframe and you should be good to go :)

**Comment by iangilman** [comment]
Wonderful! This is perfect for including in http://www.artywidget.com/ (a site I'm working on for collecting and presenting code-based art). Thank you :-)

**Comment by iangilman** [comment]
Hmm… actually, this doesn't quite work for my scenario, since the embed always maintains the original aspect ratio, rather than conforming to the aspect ratio of the iframe. Might it be possible to update it with an option to allow arbitrary aspect ratio? I realize some creations might expect a specific aspect ratio, but I think plenty wouldn't mind one way or the other, and then they'd be able to be used in more contexts.

**Comment by lionleaf** [comment]
While you can embed the content of a dweet, it would be a neat feature to have the full dweet card embeddable (sp?). To include author, comments etc
