### ISSUE TITLE
A #spoiler suggestion

### ISSUE THREAD

**Issue by imscary** [lionleaf/dwitter#448]
### `#spoiler` 
**will play the dweet only when clicked on canvas for every dweet tagged with #spoiler**
the autoplay will be disabled & `recieveMessage` should work different. Is it too hard to implement this? _Similar to the discordapp's spoiler system. This is useful for #394 too_

A image should be shown before clicking the canvas. Something like:
![image](https://user-images.githubusercontent.com/34210285/66865232-7ac3c680-ef9f-11e9-9035-27d5ba496d30.png)

I think it is useful for heavy dweets, audio dweets, nsfw jokes dweets & every other kind of dweet that shouldn't be played automatically. What do you guys think?

**Comment by lionleaf** [comment]
As mentioned in #394 I definitely think this would be very useful :) Is spoiler the right term for it? We generally don't deal with actual spoilers, but the spoiler tag seems to be used for this purpose elsewhere. I can't think of any better term at the moment though.

Tagging this with "contributions welcome". If you feel like you want to implement this, please assign yourself and feel free to reach out to me for help / feedback.

**Comment by rep-movsd** [comment]
Since the first NSFW tweet I know of has appeared on dwitter and some of us are really in work/home situations where we need some NSFW filtration, I am going to work on this feature.
The first step will be to modify the dweet.html to be "click to reveal" if a param called "spoiler" is passed.

The exact mechanism to pass that in from the frontend can be decided - my initial idea is to check for certain hashtags - chiefly NSFW anywhere in the comments.

Or "#nsfw" in the title, and admins can step in and add the tag if the author forgets to.

**Comment by KilledByAPixel** [comment]
Thank you for doing this!

It is not my goal to offend just trying to bring more attention to dwitter and make some people laugh.
