### ISSUE TITLE
Completely clear canvas when dweet is changed including custom variables

### ISSUE THREAD

**Issue by lionleaf** [lionleaf/dwitter#93]

**Comment by aemkei** [comment]
👍 This also made it hard for me.

**Comment by joeytwiddle** [comment]
I tried deleting all the properties from `window`. But the browser didn't recreate some of them (e.g. `window.performance`) and so that idea died quickly.

I guess the idea of creating a whole new <iframe> is avoided because it would slow down the editing process, increasing the time between editing and seeing results.  But how about a compromise?  Load a new <iframe> every 40 edits, or every 1 minute, or when the mouse hovers over the Post button.  It won't catch the mistake immediately, but it should at least catch it before publishing.

**Comment by atesgoral** [comment]
One option is to take a snapshot of all default globals and then selectively deleting only globals that weren't in that initial set.

**Comment by lionleaf** [comment]
Solved
