### ISSUE TITLE
Wish List: Shortcur to clear the canvas

### ISSUE THREAD

**Issue by aemkei** [lionleaf/dwitter#97]
Currently we have to do `c.width=1080` (which is OK, because it can be used to define the stage size), but having a shortcut such as `X()` would save some bytes.

**Comment by lionleaf** [comment]
The fewest character clearing I've seen so far is c.width=2e3;  see #95 for
a discussion on more shortcuts.

On Mon, Feb 20, 2017, 08:48 Martin Kleppe <notifications@github.com> wrote:

Currently we have to do c.width=1980 (which is OK, because it can be used
to define the stage size), but having a shortcut such as X() would save
some bytes.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/lionleaf/dwitter/issues/97>, or mute the thread

**Comment by bakkot** [comment]
(`c.width^=0` is shorter.)

**Comment by iver56** [comment]
> `c.width^=0`

That's brilliant 👍 💯 Thanks!
